SELECT * FROM BOARD;

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('오늘 저녁에 하늘마당에서 보실 분','내가 치킨 쏜다','명훈쌤');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('안녕하세요','손석구입니다','석구');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('나는요 SPRING 좋은걸','아이쿠','아이유');