SELECT * FROM member;

CREATE TABLE `TB_REQUEST` (
	`REQ_NUM`	int	NOT NULL,
	`USERNAME`	varchar(30)	NOT NULL,
	`REQUEST`	varchar(100)	NOT NULL
);

ALTER TABLE `TB_REQUEST` ADD CONSTRAINT `PK_TB_REQUEST` PRIMARY KEY (
	`REQ_NUM`,
	`USERNAME`
);

ALTER TABLE `TB_REQUEST` ADD CONSTRAINT `FK_TB_USER_TO_TB_REQUEST_1` FOREIGN KEY (
	`USERNAME`
)
REFERENCES `TB_USER` (
	`USERNAME`
);